# Generated by Django 5.0 on 2024-02-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0008_attendance_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='r1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='r2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='r3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='w1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='w2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='attendance',
            name='w3',
            field=models.CharField(default='', max_length=200),
        ),
    ]
